/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Meters = number;
export interface Project {
  'area' : Meters,
  'name' : string,
  'perimeter' : Meters,
  'coordinates' : Array<[number, number]>,
}
export type ProjectId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a specific project by ID
   */
  'getProject' : ActorMethod<[ProjectId], Project>,
  /**
   * / Get all project IDs for the caller
   */
  'getProjectIds' : ActorMethod<[], Array<ProjectId>>,
  /**
   * / Get all project IDs for the caller, sorted by creation time (most recent first)
   */
  'getProjectIdsByCreationTime' : ActorMethod<[], Array<ProjectId>>,
  /**
   * / Get all projects for the caller
   */
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Remove a project for the caller
   */
  'removeProject' : ActorMethod<[ProjectId], ProjectId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Add or update a project for the caller
   */
  'saveProject' : ActorMethod<[Project], ProjectId>,
  /**
   * / Get projects for the caller, filtered by a search term in the name (case-insensitive).
   */
  'searchProjects' : ActorMethod<[string], Array<Project>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];