/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ProjectId = IDL.Nat;
export const Meters = IDL.Float64;
export const Project = IDL.Record({
  'area' : Meters,
  'name' : IDL.Text,
  'perimeter' : Meters,
  'coordinates' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([ProjectId], [Project], ['query']),
  'getProjectIds' : IDL.Func([], [IDL.Vec(ProjectId)], ['query']),
  'getProjectIdsByCreationTime' : IDL.Func([], [IDL.Vec(ProjectId)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeProject' : IDL.Func([ProjectId], [ProjectId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProject' : IDL.Func([Project], [ProjectId], []),
  'searchProjects' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ProjectId = IDL.Nat;
  const Meters = IDL.Float64;
  const Project = IDL.Record({
    'area' : Meters,
    'name' : IDL.Text,
    'perimeter' : Meters,
    'coordinates' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([ProjectId], [Project], ['query']),
    'getProjectIds' : IDL.Func([], [IDL.Vec(ProjectId)], ['query']),
    'getProjectIdsByCreationTime' : IDL.Func(
        [],
        [IDL.Vec(ProjectId)],
        ['query'],
      ),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeProject' : IDL.Func([ProjectId], [ProjectId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProject' : IDL.Func([Project], [ProjectId], []),
    'searchProjects' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };